
ELASTICSEARCH: localhost:9200

ES_PING_TIMEOUT: 3000
ES_STATUS_CHECK_DELAY: 10000

SERVER_UPDATE_INTERVAL_SECS: 30
ES_INDEX_CLEANUP_INTERVAL_SECS: 300

RESTART_ON_NO_LIVING_CONNECTIONS: false
NO_LIVING_CONNECTIONS_RESTART_DELAY_SECS: 10

# Client side Angular config:

# AUTH_HOSTNAME: localhost
AUTH_PORT: 3001
# AUTH_PATH: /auth

REFRESH_TOKEN_INTERVAL_MINS: 20

# API_HOSTNAME: localhost
# API_PORT: 3000
API_PATH: /api
# API_VERSION: 2

CHART_REFRESH_SECS: 0
TARGET_AGG_BUCKETS: 20
MAX_AGG_BUCKETS: 250
